//! # anvil-ffi
//!
//! C ABI for Anvil. Consumed by iOS (Swift / ObjC), Android (Kotlin / Java via
//! JNI), and native desktop wrappers that prefer FFI over a Rust dependency.
//!
//! Rules for this crate:
//!
//! 1. Every entry point is `#[no_mangle] extern "C"`.
//! 2. Every entry point wraps its body in `std::panic::catch_unwind` — panics
//!    must never cross the FFI boundary.
//! 3. Handles are opaque (`*mut AnvilHandle`); destroyed via `anvil_destroy`.
//! 4. All returned pointers are owned by the caller; the C header generated by
//!    `cbindgen` documents ownership per function.
//! 5. Events cross the boundary via a single function-pointer callback
//!    registered at init time.
//!
//! Implementations land in Phase 3. Until then this file is a skeleton.

#![allow(clippy::missing_safety_doc)]

/// Opaque handle passed back to the host.
pub struct AnvilHandle {
    _private: (),
}
