// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/phone.dart';

import 'dart:async';
import 'dart:convert';

import 'frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  RustStreamSink<PhoneChange> dco_decode_StreamSink_phone_change_Sse(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  Account dco_decode_account(dynamic raw);

  @protected
  AudioDevice dco_decode_audio_device(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  Account dco_decode_box_autoadd_account(dynamic raw);

  @protected
  bool dco_decode_box_autoadd_bool(dynamic raw);

  @protected
  CallingChange dco_decode_box_autoadd_calling_change(dynamic raw);

  @protected
  CallingSettings dco_decode_box_autoadd_calling_settings(dynamic raw);

  @protected
  Quality dco_decode_box_autoadd_quality(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw);

  @protected
  Call dco_decode_call(dynamic raw);

  @protected
  CallState dco_decode_call_state(dynamic raw);

  @protected
  CallingChange dco_decode_calling_change(dynamic raw);

  @protected
  CallingSettings dco_decode_calling_settings(dynamic raw);

  @protected
  Direction dco_decode_direction(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  List<AudioDevice> dco_decode_list_audio_device(dynamic raw);

  @protected
  List<Call> dco_decode_list_call(dynamic raw);

  @protected
  List<Person> dco_decode_list_person(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<Recent> dco_decode_list_recent(dynamic raw);

  @protected
  List<Voicemail> dco_decode_list_voicemail(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  Account? dco_decode_opt_box_autoadd_account(dynamic raw);

  @protected
  bool? dco_decode_opt_box_autoadd_bool(dynamic raw);

  @protected
  CallingSettings? dco_decode_opt_box_autoadd_calling_settings(dynamic raw);

  @protected
  Quality? dco_decode_opt_box_autoadd_quality(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw);

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw);

  @protected
  Person dco_decode_person(dynamic raw);

  @protected
  PhoneChange dco_decode_phone_change(dynamic raw);

  @protected
  PhoneState dco_decode_phone_state(dynamic raw);

  @protected
  Quality dco_decode_quality(dynamic raw);

  @protected
  Recent dco_decode_recent(dynamic raw);

  @protected
  Registration dco_decode_registration(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  Voicemail dco_decode_voicemail(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  RustStreamSink<PhoneChange> sse_decode_StreamSink_phone_change_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  Account sse_decode_account(SseDeserializer deserializer);

  @protected
  AudioDevice sse_decode_audio_device(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  Account sse_decode_box_autoadd_account(SseDeserializer deserializer);

  @protected
  bool sse_decode_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  CallingChange sse_decode_box_autoadd_calling_change(
    SseDeserializer deserializer,
  );

  @protected
  CallingSettings sse_decode_box_autoadd_calling_settings(
    SseDeserializer deserializer,
  );

  @protected
  Quality sse_decode_box_autoadd_quality(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  Call sse_decode_call(SseDeserializer deserializer);

  @protected
  CallState sse_decode_call_state(SseDeserializer deserializer);

  @protected
  CallingChange sse_decode_calling_change(SseDeserializer deserializer);

  @protected
  CallingSettings sse_decode_calling_settings(SseDeserializer deserializer);

  @protected
  Direction sse_decode_direction(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  List<AudioDevice> sse_decode_list_audio_device(SseDeserializer deserializer);

  @protected
  List<Call> sse_decode_list_call(SseDeserializer deserializer);

  @protected
  List<Person> sse_decode_list_person(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<Recent> sse_decode_list_recent(SseDeserializer deserializer);

  @protected
  List<Voicemail> sse_decode_list_voicemail(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  Account? sse_decode_opt_box_autoadd_account(SseDeserializer deserializer);

  @protected
  bool? sse_decode_opt_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  CallingSettings? sse_decode_opt_box_autoadd_calling_settings(
    SseDeserializer deserializer,
  );

  @protected
  Quality? sse_decode_opt_box_autoadd_quality(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  Person sse_decode_person(SseDeserializer deserializer);

  @protected
  PhoneChange sse_decode_phone_change(SseDeserializer deserializer);

  @protected
  PhoneState sse_decode_phone_state(SseDeserializer deserializer);

  @protected
  Quality sse_decode_quality(SseDeserializer deserializer);

  @protected
  Recent sse_decode_recent(SseDeserializer deserializer);

  @protected
  Registration sse_decode_registration(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  Voicemail sse_decode_voicemail(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_phone_change_Sse(
    RustStreamSink<PhoneChange> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_account(Account self, SseSerializer serializer);

  @protected
  void sse_encode_audio_device(AudioDevice self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_account(Account self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_calling_change(
    CallingChange self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_calling_settings(
    CallingSettings self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_quality(Quality self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_call(Call self, SseSerializer serializer);

  @protected
  void sse_encode_call_state(CallState self, SseSerializer serializer);

  @protected
  void sse_encode_calling_change(CallingChange self, SseSerializer serializer);

  @protected
  void sse_encode_calling_settings(
    CallingSettings self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_direction(Direction self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_list_audio_device(
    List<AudioDevice> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_call(List<Call> self, SseSerializer serializer);

  @protected
  void sse_encode_list_person(List<Person> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_recent(List<Recent> self, SseSerializer serializer);

  @protected
  void sse_encode_list_voicemail(
    List<Voicemail> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_account(
    Account? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_bool(bool? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_calling_settings(
    CallingSettings? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_quality(
    Quality? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
    Uint8List? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_person(Person self, SseSerializer serializer);

  @protected
  void sse_encode_phone_change(PhoneChange self, SseSerializer serializer);

  @protected
  void sse_encode_phone_state(PhoneState self, SseSerializer serializer);

  @protected
  void sse_encode_quality(Quality self, SseSerializer serializer);

  @protected
  void sse_encode_recent(Recent self, SseSerializer serializer);

  @protected
  void sse_encode_registration(Registration self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_voicemail(Voicemail self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
