// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `devices`, `direction`, `execute`, `kind_only`, `on_runtime`, `phone`, `runtime`

/// The session kept at `session_path`, if there is one.
Future<Account?> savedAccount({required String sessionPath}) =>
    RustLib.instance.api.crateApiPhoneSavedAccount(sessionPath: sessionPath);

/// Sign in with a username and password (`place` is the server or an email
/// address), keeping the session at `session_path`.
Future<Account> signIn({
  required String place,
  required String username,
  required String password,
  String? totp,
  required String sessionPath,
}) => RustLib.instance.api.crateApiPhoneSignIn(
  place: place,
  username: username,
  password: password,
  totp: totp,
  sessionPath: sessionPath,
);

/// Start the phone from the session at `session_path`: registered, ringing,
/// and serving the control socket so `anvil-cli` can drive the app.
Future<void> startPhone({required String sessionPath}) =>
    RustLib.instance.api.crateApiPhoneStartPhone(sessionPath: sessionPath);

/// Stop the phone; the session stays signed in.
Future<void> stopPhone() => RustLib.instance.api.crateApiPhoneStopPhone();

/// Sign out: the phone stops and the app's session ends at FCP.
Future<void> signOut({required String sessionPath}) =>
    RustLib.instance.api.crateApiPhoneSignOut(sessionPath: sessionPath);

/// The phone as it is now.
PhoneState phoneState() => RustLib.instance.api.crateApiPhonePhoneState();

/// Every change from now on, until the phone stops.
Stream<PhoneChange> phoneChanges() =>
    RustLib.instance.api.crateApiPhonePhoneChanges();

/// Dial a number, an extension, a name or an address; the new call's id.
Future<BigInt> placeCall({required String target}) =>
    RustLib.instance.api.crateApiPhonePlaceCall(target: target);

Future<void> answer({BigInt? call}) =>
    RustLib.instance.api.crateApiPhoneAnswer(call: call);

Future<void> decline({BigInt? call}) =>
    RustLib.instance.api.crateApiPhoneDecline(call: call);

Future<void> hangup({BigInt? call}) =>
    RustLib.instance.api.crateApiPhoneHangup(call: call);

Future<void> hold({BigInt? call, required bool on_}) =>
    RustLib.instance.api.crateApiPhoneHold(call: call, on_: on_);

Future<void> mute({BigInt? call, required bool on_}) =>
    RustLib.instance.api.crateApiPhoneMute(call: call, on_: on_);

Future<void> sendDigits({BigInt? call, required String digits}) =>
    RustLib.instance.api.crateApiPhoneSendDigits(call: call, digits: digits);

/// Blind-transfer a call to a number, an extension or an address.
Future<void> transfer({BigInt? call, required String target}) =>
    RustLib.instance.api.crateApiPhoneTransfer(call: call, target: target);

/// Join `call`'s party to `to`'s (attended transfer), ending both of ours.
Future<void> transferAttended({required BigInt call, required BigInt to}) =>
    RustLib.instance.api.crateApiPhoneTransferAttended(call: call, to: to);

/// Park a call with FCP's park code.
Future<void> park({BigInt? call}) =>
    RustLib.instance.api.crateApiPhonePark(call: call);

Future<void> setDnd({required bool on_}) =>
    RustLib.instance.api.crateApiPhoneSetDnd(on_: on_);

/// Change the calling settings: forwards, call waiting.
Future<void> setCalling({required CallingChange change}) =>
    RustLib.instance.api.crateApiPhoneSetCalling(change: change);

Future<void> markHeard({required String id}) =>
    RustLib.instance.api.crateApiPhoneMarkHeard(id: id);

Future<void> deleteVoicemail({required String id}) =>
    RustLib.instance.api.crateApiPhoneDeleteVoicemail(id: id);

/// Play a voicemail message through the speaker calls use.
Future<void> playVoicemail({required String id}) =>
    RustLib.instance.api.crateApiPhonePlayVoicemail(id: id);

Future<void> stopPlaying() => RustLib.instance.api.crateApiPhoneStopPlaying();

/// Make someone (by key, extension or name) a favourite, or not.
Future<void> favourite({required String who, required bool on_}) =>
    RustLib.instance.api.crateApiPhoneFavourite(who: who, on_: on_);

/// Use this microphone (`input`) or speaker by id, `None` for the system's
/// default, for the calls set up from now on.
Future<void> chooseAudio({required bool input, String? device}) =>
    RustLib.instance.api.crateApiPhoneChooseAudio(input: input, device: device);

/// Read the user's data from FCP again.
Future<void> refresh() => RustLib.instance.api.crateApiPhoneRefresh();

/// Who is signed in.
class Account {
  final String username;

  /// The FCP server, e.g. `https://pbx.example.com`.
  final String server;

  const Account({required this.username, required this.server});

  @override
  int get hashCode => username.hashCode ^ server.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Account &&
          runtimeType == other.runtimeType &&
          username == other.username &&
          server == other.server;
}

/// A microphone or a speaker.
class AudioDevice {
  final String id;
  final String name;
  final bool default_;

  const AudioDevice({
    required this.id,
    required this.name,
    required this.default_,
  });

  @override
  int get hashCode => id.hashCode ^ name.hashCode ^ default_.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AudioDevice &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          default_ == other.default_;
}

/// One call, as a screen shows it.
class Call {
  final BigInt id;
  final Direction direction;
  final String remote;
  final String? displayName;
  final CallState state;
  final bool held;
  final bool muted;
  final String? codec;

  /// The media is encrypted (SRTP).
  final bool encrypted;

  /// How the media is doing, once measured.
  final Quality? quality;

  /// When it connected, in Unix seconds.
  final BigInt? connectedAt;

  const Call({
    required this.id,
    required this.direction,
    required this.remote,
    this.displayName,
    required this.state,
    required this.held,
    required this.muted,
    this.codec,
    required this.encrypted,
    this.quality,
    this.connectedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      direction.hashCode ^
      remote.hashCode ^
      displayName.hashCode ^
      state.hashCode ^
      held.hashCode ^
      muted.hashCode ^
      codec.hashCode ^
      encrypted.hashCode ^
      quality.hashCode ^
      connectedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Call &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          direction == other.direction &&
          remote == other.remote &&
          displayName == other.displayName &&
          state == other.state &&
          held == other.held &&
          muted == other.muted &&
          codec == other.codec &&
          encrypted == other.encrypted &&
          quality == other.quality &&
          connectedAt == other.connectedAt;
}

/// Where a call is.
enum CallState { dialing, ringing, connected }

/// A change to the calling settings: each field left out is kept, and an
/// empty forward clears it.
class CallingChange {
  final bool? callWaiting;
  final String? forwardAll;
  final String? forwardBusy;
  final String? forwardNoAnswer;
  final String? forwardUnreachable;
  final int? noAnswerSecs;

  const CallingChange({
    this.callWaiting,
    this.forwardAll,
    this.forwardBusy,
    this.forwardNoAnswer,
    this.forwardUnreachable,
    this.noAnswerSecs,
  });

  @override
  int get hashCode =>
      callWaiting.hashCode ^
      forwardAll.hashCode ^
      forwardBusy.hashCode ^
      forwardNoAnswer.hashCode ^
      forwardUnreachable.hashCode ^
      noAnswerSecs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CallingChange &&
          runtimeType == other.runtimeType &&
          callWaiting == other.callWaiting &&
          forwardAll == other.forwardAll &&
          forwardBusy == other.forwardBusy &&
          forwardNoAnswer == other.forwardNoAnswer &&
          forwardUnreachable == other.forwardUnreachable &&
          noAnswerSecs == other.noAnswerSecs;
}

/// The user's calling settings, as FCP has them.
class CallingSettings {
  final bool dnd;
  final bool callWaiting;
  final String? forwardAll;
  final String? forwardBusy;
  final String? forwardNoAnswer;
  final String? forwardUnreachable;
  final int? noAnswerSecs;

  const CallingSettings({
    required this.dnd,
    required this.callWaiting,
    this.forwardAll,
    this.forwardBusy,
    this.forwardNoAnswer,
    this.forwardUnreachable,
    this.noAnswerSecs,
  });

  @override
  int get hashCode =>
      dnd.hashCode ^
      callWaiting.hashCode ^
      forwardAll.hashCode ^
      forwardBusy.hashCode ^
      forwardNoAnswer.hashCode ^
      forwardUnreachable.hashCode ^
      noAnswerSecs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CallingSettings &&
          runtimeType == other.runtimeType &&
          dnd == other.dnd &&
          callWaiting == other.callWaiting &&
          forwardAll == other.forwardAll &&
          forwardBusy == other.forwardBusy &&
          forwardNoAnswer == other.forwardNoAnswer &&
          forwardUnreachable == other.forwardUnreachable &&
          noAnswerSecs == other.noAnswerSecs;
}

/// Which way a call goes.
enum Direction { incoming, outgoing }

/// Someone in the tenant's directory.
class Person {
  final String key;
  final String name;
  final String? extension_;
  final String? department;
  final String? jobTitle;

  /// `available`, `busy`, `away`, `dnd`, `offline`, … when shown.
  final String? presence;
  final bool onCall;
  final bool favourite;

  /// What to dial.
  final String dial;

  const Person({
    required this.key,
    required this.name,
    this.extension_,
    this.department,
    this.jobTitle,
    this.presence,
    required this.onCall,
    required this.favourite,
    required this.dial,
  });

  @override
  int get hashCode =>
      key.hashCode ^
      name.hashCode ^
      extension_.hashCode ^
      department.hashCode ^
      jobTitle.hashCode ^
      presence.hashCode ^
      onCall.hashCode ^
      favourite.hashCode ^
      dial.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Person &&
          runtimeType == other.runtimeType &&
          key == other.key &&
          name == other.name &&
          extension_ == other.extension_ &&
          department == other.department &&
          jobTitle == other.jobTitle &&
          presence == other.presence &&
          onCall == other.onCall &&
          favourite == other.favourite &&
          dial == other.dial;
}

/// What changed: the screen redraws from [`phone_state`] and may say why.
class PhoneChange {
  /// `registration`, `call`, `call_ended`, `message_waiting`, `dnd`,
  /// `brand`, `transfer_progress`, `calling`, `recents`, `people`,
  /// `person`, `voicemail`, `audio`, `playing`.
  final String kind;

  /// The call it is about, if any.
  final BigInt? call;

  /// Why a call ended, or a registration failed.
  final String? reason;

  const PhoneChange({required this.kind, this.call, this.reason});

  @override
  int get hashCode => kind.hashCode ^ call.hashCode ^ reason.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PhoneChange &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          call == other.call &&
          reason == other.reason;
}

/// The phone as a screen shows it.
class PhoneState {
  final String aor;
  final Registration registration;
  final List<Call> calls;
  final int voicemailNew;
  final bool? dnd;

  /// The tenant's brand: its app name, colours (`#RRGGBB`) and logo.
  final String? brandName;
  final String? brandPrimary;
  final Uint8List? brandLogo;

  /// Signed in to FCP: the calling settings, once read.
  final CallingSettings? calling;

  /// The latest calls, newest first.
  final List<Recent> recents;
  final List<Person> people;

  /// The mailbox's messages, newest first.
  final List<Voicemail> voicemail;
  final List<AudioDevice> inputs;
  final List<AudioDevice> outputs;

  /// The devices chosen; `None` is the system's default.
  final String? input;
  final String? output;

  /// The voicemail message playing.
  final String? playing;

  const PhoneState({
    required this.aor,
    required this.registration,
    required this.calls,
    required this.voicemailNew,
    this.dnd,
    this.brandName,
    this.brandPrimary,
    this.brandLogo,
    this.calling,
    required this.recents,
    required this.people,
    required this.voicemail,
    required this.inputs,
    required this.outputs,
    this.input,
    this.output,
    this.playing,
  });

  @override
  int get hashCode =>
      aor.hashCode ^
      registration.hashCode ^
      calls.hashCode ^
      voicemailNew.hashCode ^
      dnd.hashCode ^
      brandName.hashCode ^
      brandPrimary.hashCode ^
      brandLogo.hashCode ^
      calling.hashCode ^
      recents.hashCode ^
      people.hashCode ^
      voicemail.hashCode ^
      inputs.hashCode ^
      outputs.hashCode ^
      input.hashCode ^
      output.hashCode ^
      playing.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PhoneState &&
          runtimeType == other.runtimeType &&
          aor == other.aor &&
          registration == other.registration &&
          calls == other.calls &&
          voicemailNew == other.voicemailNew &&
          dnd == other.dnd &&
          brandName == other.brandName &&
          brandPrimary == other.brandPrimary &&
          brandLogo == other.brandLogo &&
          calling == other.calling &&
          recents == other.recents &&
          people == other.people &&
          voicemail == other.voicemail &&
          inputs == other.inputs &&
          outputs == other.outputs &&
          input == other.input &&
          output == other.output &&
          playing == other.playing;
}

/// A connected call's media, as last measured.
class Quality {
  final int jitterMs;
  final int packetLossPermille;
  final int? rttMs;

  const Quality({
    required this.jitterMs,
    required this.packetLossPermille,
    this.rttMs,
  });

  @override
  int get hashCode =>
      jitterMs.hashCode ^ packetLossPermille.hashCode ^ rttMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Quality &&
          runtimeType == other.runtimeType &&
          jitterMs == other.jitterMs &&
          packetLossPermille == other.packetLossPermille &&
          rttMs == other.rttMs;
}

/// One call in the user's history.
class Recent {
  final String id;
  final Direction direction;
  final String remote;
  final String? displayName;
  final bool missed;

  /// RFC 3339.
  final String startedAt;
  final BigInt? durationSecs;

  const Recent({
    required this.id,
    required this.direction,
    required this.remote,
    this.displayName,
    required this.missed,
    required this.startedAt,
    this.durationSecs,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      direction.hashCode ^
      remote.hashCode ^
      displayName.hashCode ^
      missed.hashCode ^
      startedAt.hashCode ^
      durationSecs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Recent &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          direction == other.direction &&
          remote == other.remote &&
          displayName == other.displayName &&
          missed == other.missed &&
          startedAt == other.startedAt &&
          durationSecs == other.durationSecs;
}

/// Whether the account is registered.
enum Registration { unregistered, registering, registered, failed }

/// One voicemail message.
class Voicemail {
  final String id;
  final String caller;
  final String? callerName;
  final bool new_;
  final bool urgent;
  final BigInt durationSecs;
  final String? transcription;

  /// RFC 3339.
  final String receivedAt;

  const Voicemail({
    required this.id,
    required this.caller,
    this.callerName,
    required this.new_,
    required this.urgent,
    required this.durationSecs,
    this.transcription,
    required this.receivedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      caller.hashCode ^
      callerName.hashCode ^
      new_.hashCode ^
      urgent.hashCode ^
      durationSecs.hashCode ^
      transcription.hashCode ^
      receivedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Voicemail &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          caller == other.caller &&
          callerName == other.callerName &&
          new_ == other.new_ &&
          urgent == other.urgent &&
          durationSecs == other.durationSecs &&
          transcription == other.transcription &&
          receivedAt == other.receivedAt;
}
