// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `execute`, `kind_only`, `on_runtime`, `phone`, `runtime`

/// The session kept at `session_path`, if there is one.
Future<Account?> savedAccount({required String sessionPath}) =>
    RustLib.instance.api.crateApiPhoneSavedAccount(sessionPath: sessionPath);

/// Sign in with a username and password (`place` is the server or an email
/// address), keeping the session at `session_path`.
Future<Account> signIn({
  required String place,
  required String username,
  required String password,
  String? totp,
  required String sessionPath,
}) => RustLib.instance.api.crateApiPhoneSignIn(
  place: place,
  username: username,
  password: password,
  totp: totp,
  sessionPath: sessionPath,
);

/// Start the phone from the session at `session_path`: registered, ringing,
/// and serving the control socket so `anvil-cli` can drive the app.
Future<void> startPhone({required String sessionPath}) =>
    RustLib.instance.api.crateApiPhoneStartPhone(sessionPath: sessionPath);

/// Stop the phone; the session stays signed in.
Future<void> stopPhone() => RustLib.instance.api.crateApiPhoneStopPhone();

/// Sign out: the phone stops and the app's session ends at FCP.
Future<void> signOut({required String sessionPath}) =>
    RustLib.instance.api.crateApiPhoneSignOut(sessionPath: sessionPath);

/// The phone as it is now.
PhoneState phoneState() => RustLib.instance.api.crateApiPhonePhoneState();

/// Every change from now on, until the phone stops.
Stream<PhoneChange> phoneChanges() =>
    RustLib.instance.api.crateApiPhonePhoneChanges();

/// Dial a number, an extension, a name or an address; the new call's id.
Future<BigInt> placeCall({required String target}) =>
    RustLib.instance.api.crateApiPhonePlaceCall(target: target);

Future<void> answer({BigInt? call}) =>
    RustLib.instance.api.crateApiPhoneAnswer(call: call);

Future<void> decline({BigInt? call}) =>
    RustLib.instance.api.crateApiPhoneDecline(call: call);

Future<void> hangup({BigInt? call}) =>
    RustLib.instance.api.crateApiPhoneHangup(call: call);

Future<void> hold({BigInt? call, required bool on_}) =>
    RustLib.instance.api.crateApiPhoneHold(call: call, on_: on_);

Future<void> mute({BigInt? call, required bool on_}) =>
    RustLib.instance.api.crateApiPhoneMute(call: call, on_: on_);

Future<void> sendDigits({BigInt? call, required String digits}) =>
    RustLib.instance.api.crateApiPhoneSendDigits(call: call, digits: digits);

/// Who is signed in.
class Account {
  final String username;

  /// The FCP server, e.g. `https://pbx.example.com`.
  final String server;

  const Account({required this.username, required this.server});

  @override
  int get hashCode => username.hashCode ^ server.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Account &&
          runtimeType == other.runtimeType &&
          username == other.username &&
          server == other.server;
}

/// One call, as a screen shows it.
class Call {
  final BigInt id;
  final Direction direction;
  final String remote;
  final String? displayName;
  final CallState state;
  final bool held;
  final bool muted;
  final String? codec;

  const Call({
    required this.id,
    required this.direction,
    required this.remote,
    this.displayName,
    required this.state,
    required this.held,
    required this.muted,
    this.codec,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      direction.hashCode ^
      remote.hashCode ^
      displayName.hashCode ^
      state.hashCode ^
      held.hashCode ^
      muted.hashCode ^
      codec.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Call &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          direction == other.direction &&
          remote == other.remote &&
          displayName == other.displayName &&
          state == other.state &&
          held == other.held &&
          muted == other.muted &&
          codec == other.codec;
}

/// Where a call is.
enum CallState { dialing, ringing, connected }

/// Which way a call goes.
enum Direction { incoming, outgoing }

/// What changed: the screen redraws from [`phone_state`] and may say why.
class PhoneChange {
  /// `registration`, `call`, `call_ended`, `message_waiting`, `dnd`,
  /// `transfer_progress`.
  final String kind;

  /// The call it is about, if any.
  final BigInt? call;

  /// Why a call ended, or a registration failed.
  final String? reason;

  const PhoneChange({required this.kind, this.call, this.reason});

  @override
  int get hashCode => kind.hashCode ^ call.hashCode ^ reason.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PhoneChange &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          call == other.call &&
          reason == other.reason;
}

/// The phone as a screen shows it.
class PhoneState {
  final String aor;
  final Registration registration;
  final List<Call> calls;
  final int voicemailNew;
  final bool? dnd;

  /// The tenant's brand: its app name, colours (`#RRGGBB`) and logo.
  final String? brandName;
  final String? brandPrimary;
  final Uint8List? brandLogo;

  const PhoneState({
    required this.aor,
    required this.registration,
    required this.calls,
    required this.voicemailNew,
    this.dnd,
    this.brandName,
    this.brandPrimary,
    this.brandLogo,
  });

  @override
  int get hashCode =>
      aor.hashCode ^
      registration.hashCode ^
      calls.hashCode ^
      voicemailNew.hashCode ^
      dnd.hashCode ^
      brandName.hashCode ^
      brandPrimary.hashCode ^
      brandLogo.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PhoneState &&
          runtimeType == other.runtimeType &&
          aor == other.aor &&
          registration == other.registration &&
          calls == other.calls &&
          voicemailNew == other.voicemailNew &&
          dnd == other.dnd &&
          brandName == other.brandName &&
          brandPrimary == other.brandPrimary &&
          brandLogo == other.brandLogo;
}

/// Whether the account is registered.
enum Registration { unregistered, registering, registered, failed }
