// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `updater`

/// This copy's version.
String appVersion() => RustLib.instance.api.crateApiUpdateAppVersion();

/// The latest release, when it is newer than this copy.
Future<UpdateInfo?> checkForUpdate() =>
    RustLib.instance.api.crateApiUpdateCheckForUpdate();

/// Fetch the update found, checked against its manifest.
Future<void> downloadUpdate() =>
    RustLib.instance.api.crateApiUpdateDownloadUpdate();

/// Install the update fetched once the app has quit, and start it again.
/// The app quits right after.
Future<void> installUpdate() =>
    RustLib.instance.api.crateApiUpdateInstallUpdate();

/// A newer release, as the app shows it.
class UpdateInfo {
  final String version;

  /// The release's page.
  final String notes;

  /// This copy can install it itself.
  final bool canInstall;

  /// Why not, when it cannot.
  final String? reason;

  /// The file to install by hand, when it cannot.
  final String? download;

  const UpdateInfo({
    required this.version,
    required this.notes,
    required this.canInstall,
    this.reason,
    this.download,
  });

  @override
  int get hashCode =>
      version.hashCode ^
      notes.hashCode ^
      canInstall.hashCode ^
      reason.hashCode ^
      download.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UpdateInfo &&
          runtimeType == other.runtimeType &&
          version == other.version &&
          notes == other.notes &&
          canInstall == other.canInstall &&
          reason == other.reason &&
          download == other.download;
}
